name: test_parser

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  my_testing:
    runs-on: ubuntu-latest
    steps:
    - name: Hello Word
      run: echo "Hello Word from testing"
  
  my_depoly:
    runs-on: ubuntu-slim
    steps:
      - name: Two steps
        run: "TWO Steps from deploy"
      
    
            
    
        
